package de.hafni.minierp.exception;

public enum FehlerCode {

    KRANZ_TYP_FEHLT,
    KRANZ_MATERIAL_FEHLT,
    KRANZ_HOEHE_UNGUELTIG,
    KRANZ_DAEMMUNG_UNGUELTIG,

    FUELLUNG_ART_FEHLT,
    FUELLUNG_AUSFUEHRUNG_FEHLT,
    FUELLUNG_DICKE_UNGUELTIG,
    FUELLUNG_UG_WERT_UNGUELTIG,
    FUELLUNG_LICHTTRANSMISSION_UNGUELTIG,
    FUELLUNG_SOLARFAKTOR_UNGUELTIG,

    ANTRIEB_ART_FEHLT,
    ANTRIEB_SPANNUNG_FEHLT,
    ANTRIEB_HUB_UNGUELTIG,
    ANTRIEB_KRAFT_UNGUELTIG,
    ANTRIEB_STROM_UNGUELTIG,

    STEUERUNG_SPANNUNG_FEHLT,
    STEUERUNG_STROM_UNGUELTIG,

    ANTRIEBSSYSTEM_ANTRIEBE_FEHLEN,
    ANTRIEBSSYSTEM_ANZAHL_UNGUELTIG,
    
    
    PROJEKT_BREITE_UNGUELTIG,
    PROJEKT_LAENGE_UNGUELTIG,
    PROJEKT_DACHNEIGUNG_UNGUELTIG,

    PRODUKTFAMILIE_CODE_FEHLT,
    PRODUKTFAMILIE_BEZEICHNUNG_FEHLT,

    KONFIGURATION_NUMMER_FEHLT,
    KONFIGURATION_FUNKTION_FEHLT,
    KONFIGURATION_PROJEKTANFORDERUNGEN_FEHLEN,
    KONFIGURATION_PRODUKTFAMILIE_FEHLT,
    KONFIGURATION_AUFSETZKRANZ_FEHLT,
    KONFIGURATION_FESTER_RAHMEN_FEHLT,
    KONFIGURATION_FUELLUNG_FEHLT,
    KUNDE_NUMMER_FEHLT,
    KUNDE_NAME_FEHLT,

    POSITION_NUMMER_UNGUELTIG,
    POSITION_MENGE_UNGUELTIG,
    POSITION_PREIS_UNGUELTIG,
    POSITION_RABATT_UNGUELTIG,
    POSITION_KONFIGURATION_FEHLT,

    AUFTRAG_NUMMER_FEHLT,
    AUFTRAG_KUNDE_FEHLT,
    AUFTRAG_POSITIONEN_FEHLEN,

    AUFTRAG_STATUSWECHSEL_UNGUELTIG,
    AUFTRAG_KEINE_POSITIONEN,
    AUFTRAG_TECHNISCH_NICHT_FREIGEGEBEN,
    PRODUKTION_NUMMER_FEHLT,
    PRODUKTION_AUFTRAG_FEHLT,
    PRODUKTION_AUFTRAG_NICHT_FREIGEGEBEN,
    PRODUKTION_STATUSWECHSEL_UNGUELTIG, ZAHLUNG_UEBERSTEIGT_RESTBETRAG, ZAHLUNG_DATUM_FEHLT, ZAHLUNG_BETRAG_UNGUELTIG, KALKULATION_AUFTRAG_FEHLT, KALKULATION_MATERIALKOSTEN_UNGUELTIG, KALKULATION_PRODUKTIONSKOSTEN_UNGUELTIG, RECHNUNG_NUMMER_FEHLT, RECHNUNG_AUFTRAG_FEHLT, RECHNUNG_DATUM_FEHLT, RECHNUNG_FAELLIGKEIT_UNGUELTIG, RECHNUNG_TVA_FEHLT
    
}