CREATE TABLE kunden (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kunden_nummer VARCHAR(50) NOT NULL UNIQUE,
    firmen_name VARCHAR(200) NOT NULL
);

CREATE TABLE antriebssysteme (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    steuerung_spannung VARCHAR(255),
    steuerung_max_strom_ampere NUMERIC(8,3),

    CONSTRAINT chk_steuerung_spannung
        CHECK (
            steuerung_spannung IS NULL
            OR steuerung_spannung IN ('AC_230_V', 'DC_24_V')
        )
);

CREATE TABLE antriebe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    art VARCHAR(255) NOT NULL,
    versorgungs_spannung VARCHAR(255) NOT NULL,

    hub_mm INTEGER NOT NULL,
    kraft_newton INTEGER NOT NULL,
    nennstrom_ampere NUMERIC(8,3) NOT NULL,

    antriebssystem_id BIGINT NOT NULL,

    CONSTRAINT chk_antrieb_art
        CHECK (
            art IN ('KETTENANTRIEB', 'LINEARANTRIEB')
        ),

    CONSTRAINT chk_antrieb_spannung
        CHECK (
            versorgungs_spannung IN ('AC_230_V', 'DC_24_V')
        ),

    CONSTRAINT fk_antrieb_antriebssystem
        FOREIGN KEY (antriebssystem_id)
        REFERENCES antriebssysteme(id)
);

CREATE TABLE lichtkuppel_konfigurationen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    konfigurations_nummer VARCHAR(50) NOT NULL UNIQUE,

    produkt_code VARCHAR(100) NOT NULL,
    produkt_bezeichnung VARCHAR(200) NOT NULL,

    funktion VARCHAR(30) NOT NULL,
    technischer_status VARCHAR(30) NOT NULL,

    dach_oeffnung_breite_mm INTEGER,
    dach_oeffnung_laenge_mm INTEGER,
    dach_neigung_grad DOUBLE PRECISION,

    kranz_typ VARCHAR(255),
    kranz_material VARCHAR(255),
    kranz_hoehe_mm INTEGER,
    kranz_daemmstaerke_mm INTEGER,

    fester_rahmen_material VARCHAR(255),
    fester_rahmen_thermisch_getrennt BOOLEAN,

    fuellung_art VARCHAR(255),
    fuellung_ausfuehrung VARCHAR(255),
    fuellung_dicke_mm INTEGER,
    fuellung_ug_wert NUMERIC(8,3),
    fuellung_lichttransmission NUMERIC(5,2),
    fuellung_solarfaktor NUMERIC(5,2),

    oeffnungsrahmen_material VARCHAR(255),
    oeffnungsrahmen_thermisch_getrennt BOOLEAN,
    oeffnungsrahmen_gewicht_kg NUMERIC(8,2),

    antriebssystem_id BIGINT UNIQUE,

    CONSTRAINT chk_lichtkuppel_funktion
        CHECK (
            funktion IN ('FEST', 'LUEFTUNG', 'RAUCHABZUG')
        ),

    CONSTRAINT chk_technischer_status
        CHECK (
            technischer_status IN (
                'ENTWURF',
                'IN_PRUEFUNG',
                'FREIGABEBEREIT',
                'FREIGEGEBEN',
                'GESPERRT'
            )
        ),

    CONSTRAINT chk_kranz_typ
        CHECK (
            kranz_typ IS NULL
            OR kranz_typ IN (
                'STANDARD',
                'RENOVIERUNG',
                'MIT_GEFAELLE'
            )
        ),

    CONSTRAINT chk_kranz_material
        CHECK (
            kranz_material IS NULL
            OR kranz_material IN (
                'VERZINKTER_STAHL',
                'ALUMINIUM',
                'PVC',
                'POLYCARBONAT',
                'GLAS'
            )
        ),

    CONSTRAINT chk_fester_rahmen_material
        CHECK (
            fester_rahmen_material IS NULL
            OR fester_rahmen_material IN (
                'VERZINKTER_STAHL',
                'ALUMINIUM',
                'PVC',
                'POLYCARBONAT',
                'GLAS'
            )
        ),

    CONSTRAINT chk_fuellung_art
        CHECK (
            fuellung_art IS NULL
            OR fuellung_art IN (
                'PCA',
                'ALUMINIUM',
                'GLAS'
            )
        ),

    CONSTRAINT chk_fuellung_ausfuehrung
        CHECK (
            fuellung_ausfuehrung IS NULL
            OR fuellung_ausfuehrung IN (
                'OPAL',
                'TRANSPARENT',
                'WAERMEREDUKTION'
            )
        ),

    CONSTRAINT chk_oeffnungsrahmen_material
        CHECK (
            oeffnungsrahmen_material IS NULL
            OR oeffnungsrahmen_material IN (
                'VERZINKTER_STAHL',
                'ALUMINIUM',
                'PVC',
                'POLYCARBONAT',
                'GLAS'
            )
        ),

    CONSTRAINT fk_konfiguration_antriebssystem
        FOREIGN KEY (antriebssystem_id)
        REFERENCES antriebssysteme(id)
);

CREATE TABLE auftraege (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    auftrags_nummer VARCHAR(50) NOT NULL UNIQUE,

    status VARCHAR(30) NOT NULL,

    kunde_id BIGINT NOT NULL,

    CONSTRAINT chk_auftrags_status
        CHECK (
            status IN (
                'ENTWURF',
                'TECHNISCH_GEPRUEFT',
                'FREIGEGEBEN',
                'IN_PRODUKTION',
                'PRODUZIERT',
                'GELIEFERT',
                'ABGESCHLOSSEN',
                'STORNIERT'
            )
        ),

    CONSTRAINT fk_auftrag_kunde
        FOREIGN KEY (kunde_id)
        REFERENCES kunden(id)
);

CREATE TABLE auftrags_positionen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    positions_nummer INTEGER NOT NULL,
    menge INTEGER NOT NULL,

    einzel_preis_ht NUMERIC(12,2) NOT NULL,
    rabatt_prozent NUMERIC(5,2) NOT NULL,

    auftrag_id BIGINT NOT NULL,
    konfiguration_id BIGINT NOT NULL UNIQUE,

    CONSTRAINT fk_position_auftrag
        FOREIGN KEY (auftrag_id)
        REFERENCES auftraege(id),

    CONSTRAINT fk_position_konfiguration
        FOREIGN KEY (konfiguration_id)
        REFERENCES lichtkuppel_konfigurationen(id)
);

CREATE INDEX idx_auftrag_kunde
    ON auftraege(kunde_id);

CREATE INDEX idx_position_auftrag
    ON auftrags_positionen(auftrag_id);

CREATE INDEX idx_antrieb_system
    ON antriebe(antriebssystem_id);