CREATE TABLE produktionsauftraege (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    produktions_nummer VARCHAR(50) NOT NULL UNIQUE,

    auftrag_id BIGINT NOT NULL,

    geplanter_start DATE NOT NULL,

    status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_produktionsauftrag_auftrag
        FOREIGN KEY (auftrag_id)
        REFERENCES auftraege(id),

    CONSTRAINT chk_produktionsauftrag_status
        CHECK (
            status IN (
                'GEPLANT',
                'IN_PRODUKTION',
                'PRODUZIERT',
                'ABGESCHLOSSEN'
            )
        )
);

CREATE INDEX idx_produktionsauftrag_auftrag
    ON produktionsauftraege(auftrag_id);

CREATE INDEX idx_produktionsauftrag_status
    ON produktionsauftraege(status);